### ISSUE TITLE
Open for contributions for Hacktoberfest 2020

### ISSUE THREAD

**Issue by dhritippaul** [dhritippaul/Data-Structure-Algorithm#8]
Do contribute any necessary algo / DS and grow the repo!

**Comment by ITES7321** [comment]
Hi! Can I help contribute for Hacktoberfest? Thanks!

**Comment by ITES7321** [comment]
#11

**Comment by mshinh** [comment]
Hey, I'd like to add doubly linked list with sentinel nodes implementation in C++
